Meteor.startup(function () {


  console.log(AdminDashboard);

  AdminDashboard.addSidebarItem('數據分析', AdminDashboard.path('/analytics'), {
    icon: 'line-chart'
  })

  if (Meteor.isClient) {

    if (Config.defaultLanguage) {
      return TAPi18n.setLanguage(Config.defaultLanguage);
    } else {
      return TAPi18n.setLanguage('en');
    }
  }
});

// ---
// generated by coffee-script 1.9.2