Meteor.startup(function () {
  
  if (Meteor.isClient) {

    Meteor.subscribe("reservations");
    Meteor.subscribe("rooms");
    Meteor.subscribe("centers");

    if (Config.defaultLanguage) {
      return TAPi18n.setLanguage(Config.defaultLanguage);
    } else {
      return TAPi18n.setLanguage('en');
    }
  }
});

// ---
// generated by coffee-script 1.9.2