if (Meteor.isClient) {
  Template.registerHelper('momentumIRTransition', function () {
    return function (from, to, element) {
      return "fade";
    };
  });
}

// ---
// generated by coffee-script 1.9.2