CommentsSchema = undefined
@Comments = new (Meteor.Collection)('comments')
CommentsSchema = new SimpleSchema(
  doc:
    type: String
    regEx: SimpleSchema.RegEx.Id
  owner:
    type: String
    regEx: SimpleSchema.RegEx.Id
    autoform: options: ->
      _.map Meteor.users.find().fetch(), (user) ->
        {
          label: user.emails[0].address
          value: user._id
        }
  createdAt:
    type: Date
    autoValue: ->
      if @isInsert
        return new Date
      return
  content:
    type: String
    label: 'Comment')
Comments.attachSchema CommentsSchema
# ---
# generated by coffee-script 1.9.2

# ---
# generated by js2coffee 2.2.0