Router.map(function () {

  this.route("home", {
    path: "/",
    layoutTemplate: "homeLayout"
  });

  // this.route('analytics', {
  //   path: AdminDashboard.path('analytics'),
  //   layoutTemplate: 'masterLayout',

  //   onAfterAction: function () {
  //     Session.set('admin_title', 'Analytics');
  //   }
  // });

  // AdminController = RouteController.extend({
  //   template: 'hello',

  //   waitOn: function () {

  //   },

  //   data: function () {}
  // });


  // return this.route("dashboard", {
  //   path: "/dashboard",
  //   waitOn: function () {
  //     return [
  //       Meteor.subscribe('attachments'),

  //       subs.subscribe('attachments'),
  //       subs.subscribe('posts'),
  //       subs.subscribe('comments'),
  //       subs.subscribe('reservations'),
  //       subs.subscribe('customers'),
  //       subs.subscribe('centers'),
  //       subs.subscribe('rooms'),
  //       subs.subscribe('districts'),
  //       subs.subscribe('roomTypes'),
  //       subs.subscribe('roomStatus')
  //     ];
  //   },
  //   data: function () {
  //     return {
  //       posts: Posts.find({}, {
  //         sort: {
  //           createdAt: -1
  //         }
  //       }).fetch()
  //     };
  //   }
  // });
});

// ---
// generated by coffee-script 1.9.2