Template.navbar.events({
  'change #sliding-menu-controller': function (e) {
    return $('body')[e.currentTarget.checked ? 'addClass' : 'removeClass']('no-overflow');
  },
  'click .sliding-menu a': function () {
    return $('#sliding-menu-controller').prop('checked', false);
  }
});

// ---
// generated by coffee-script 1.9.2